title: MLCV@LCLS
description: MLCV group at LCLS
url: https://lcls-mlcv.github.io
baseurl: ""
lang: en
timezone: America/Los_Angeles

email:
github_username: lcls-mlcv
bluesky_url: lcls-mlcv.bsky.social
icon: lcls.png

navbar_fixed: true
footer_fixed: true
max_width: 930px
last_updated: true
enable_darkmode: true
repo_theme_light: ambient_gradient
repo_theme_dark: dark

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

include:
  - _pages

exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - clear-history.sh
  - requirements.txt
  - tools/
  - vendor/

keep_files:
  - CNAME
  - .nojekyll

collections:
  news:
    output: true
    permalink: /news/:name/
  projects:
    output: true
    permalink: /projects/:name/
  talks:
    output: true
    permalink: /talks/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: projects
  - scope:
      path: ""
      type: talks
    values:
      layout: talks
  - scope:
      path: ""
      type: news
    values:
      layout: post
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

project_categories:
  - Computational Imaging
  - Automation
  - Data Reduction

talk_categories:
  - Past
